#!/bin/sh
~/AFLplusplus/afl-fuzz -i in/ -o out/ -x nethack.dict -t50 -M fuzzer00 -p exploit ~/NetHack/src/nethack &
~/AFLplusplus/afl-fuzz -i in/ -o out/ -x nethack.dict -t50 -S fuzzer01 -p coe ~/NetHack/src/nethack 1>/dev/null 2>&1 &
~/AFLplusplus/afl-fuzz -i in/ -o out/ -x nethack.dict -t50 -S fuzzer02 -p fast ~/NetHack/src/nethack 1>/dev/null 2>&1 &
~/AFLplusplus/afl-fuzz -i in/ -o out/ -x nethack.dict -t50 -S fuzzer03 -p explore ~/NetHack/src/nethack 1>/dev/null 2>&1 &
~/AFLplusplus/afl-fuzz -i in/ -o out/ -x nethack.dict -t50 -S fuzzer04 -p coe ~/NetHack/src/nethack 1>/dev/null 2>&1 &
~/AFLplusplus/afl-fuzz -i in/ -o out/ -x nethack.dict -t50 -S fuzzer05 -p fast ~/NetHack/src/nethack 1>/dev/null 2>&1 &
~/AFLplusplus/afl-fuzz -i in/ -o out/ -x nethack.dict -t50 -S fuzzer06 -p explore ~/NetHack/src/nethack 1>/dev/null 2>&1 &
